# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
baseURL = "https://harry1321.github.io/"
defaultContentLanguage = "zh-tw"

enableRobotsTXT = true
summaryLength = 50

[pagination]
  pagerSize = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/configuration/taxonomies/
# set params.article.showTaxonomies = true
[taxonomies]
  category = 'categories'
  tag = 'tags'

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.googleAnalytics]
    id = 'G-4E1BCNMHM7'
  [services.x]
    disableInlineCSS = true
